name: Python Autolint
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
      - run: pip install black
      - run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          printenv | grep GITHUB
          git config --global user.name 'Python Linter'
          git config --global user.email 'autolint@users.noreply.github.com'          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git remote -v
          git branch
          git status
          black .
          git status
          git commit -am "Automatically formatted Python code with psf/black"
          git push
