name: Run pytest when core files have changed

on:
  pull_request:
    paths:
    - '.github/workflows/*.yaml'
    - 'locations/commands/*.py'
    - 'locations/middlewares/*.py'
    - 'locations/pipelines/*.py'
    - 'locations/storefinders/*.py'
    - 'locations/spiders/*.py'
    - 'locations/*.py'
    - 'tests/*.py'
    - 'Pipfile'
    - 'Pipfile.lock'


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pipenv'
    - name: Install pipenv
      run: |
        pip --quiet install pipenv
    - name: Install dependencies
      run: |
        pipenv --bare install --dev
    - name: Run pytest
      run: |
        pipenv run pytest
